### PR TITLE
Jsteinberg v1

### PR DESCRIPTION
**Pull request by smashedTuba28**

### CODE REVIEW

**Review by wtaylor41 — APPROVED** [review]
looks good to me I will start the xml and jsp files accordingly.

**Review by twetzel1 — CHANGES_REQUESTED** [review]
Testing Request Changes

**Comment by smashedTuba28** [comment]
pretended to fix changes

**Comment by smashedTuba28** [comment]
> Testing Request Changes

fixed said issues

**Review by twetzel1 — APPROVED** [review]

**Pull request merged**
